name: custom_platform_device_id_updated
description: You can get device id from platform - linux/mac/windows/android/ios/web.
version: 2.0.0
homepage: https://github.com/eslamira/custom_platform_device_id_updated

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  platform_device_id_platform_interface: ^1.0.0
  platform_device_id_macos: ^1.0.0
  platform_device_id_linux: ^1.0.0
  platform_device_id_web: ^1.0.0
  platform_device_id_windows: ^1.0.0
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

